class SurahPlayer {
  List<String> mp3 = [
    'music/fatiha.mp3',
    'music/naas.m4a',
    'music/falaq.m4a',
    'music/ikhlas.m4a',
    'music/masad.m4a',
    'music/nasr.m4a',
    'music/kaafiro.m4a',
    'music/kauhar.m4a',
    'music/maaoon.m4a',
    'music/kuroysh.m4a',
    'music/fil.m4a',
    'music/humaza.m4a',
    'music/asr.m4a',
    'music/takasur.m4a',
    'music/kuroysh.m4a',
    'music/qoriah.m4a',
    'music/adiya.m4a',
    'music/zalzala.m4a',
    'music/bayyinah.m4a',
    'music/qodr.m4a',
    'music/alaq.m4a',
    'music/tin.m4a',
    'music/sharh.m4a',
    'music/duha.m4a',
    'music/lail.m4a',
    'music/shams.m4a',
    'music/balad.m4a',
    'music/fajr.m4a',
    'music/ghoshiya.m4a',
    'music/alala.m4a',
    'music/tariq.m4a',
    'music/durooj.m4a',
    'music/inshiqoq.m4a',
    'music/mutaffifin.m4a',
    'music/infitar.m4a',
    'music/takwir.m4a',
    'music/abasa.m4a',
    'music/nazi.m4a',
    'music/naba.m4a',
  ];
}

class SurahNamed {
  List<String> named = [
    'Surah Al Fatiha ',
    ' Surah An-Naas ',
    ' Surah Al-Falaq  ',
    ' Surah Al-Ikhlaas or At-Tauhid  ',
    ' Surah Al-Masad ',
    ' Surah An-Nasr ',
    ' Surah Al-Kaafiroon ',
    ' Surah Al-Kauthar  ',
    ' Surah Al-Maa_oon  ',
    ' Surah Al-Quraish ',
    ' Surah Al-Feel  ',
    ' Surah Al-Humazah ',
    ' Surah Al-Asr  ',
    ' Surah At-Takaathur ',
    ' Surah Al-Qari_ah  ',
    ' Surah Al-Aadiyaat  ',
    ' Surah Al-Zalzalah  ',
    ' Surah Al-Baiyyinah  ',
    ' Surah Al-Qadr  ',
    ' Surah Al-Alaq ',
    ' Surah At-Tin  ',
    ' Surah Ash-Sharh  ',
    ' Surah Ad-Duha  ',
    ' Surah Al-Lail  ',
    ' Surah Ash-Shams  ',
    ' Surah Al-Balad  ',
    ' Surah Al-Fajr ',
    ' Surah Al-Ghaashiyah  ',
    ' Surah Al-A_la  ',
    ' Surah At-Tariq  ',
    ' Surah Al-Burooj ',
    ' Surah Al-Inshiqaq  ',
    ' Surah Al-Mutaffifin  ',
    ' Surah Al-Infitaar ',
    ' Surah At-Takwir  ',
    ' Surah Abasa  ',
    ' Surah An-Nazi_aat  ',
    'Surah An-Naba_  ',
  ];
}
