class SurahPlayer {
  List<String> mp3 = [
    'music/fatiha.mp3',
    'music/naas.m4a',
    'music/falaq.m4a',
    'music/ikhlas.m4a',
    'music/masad.m4a',
    'music/nasr.m4a',
    'music/kaafiro.m4a',
    'music/kauhar.m4a',
    'music/maaoon.m4a',
    'music/kuroysh.m4a',
    'music/fil.m4a',
    'music/humaza.m4a',
    'music/asr.m4a',
    'music/takasur.m4a',
    'music/kuroysh.m4a',
    'music/qoriah.m4a',
    'music/adiya.m4a',
    'music/zalzala.m4a',
    'music/bayyinah.m4a',
    'music/qodr.m4a',
    'music/alaq.m4a',
    'music/tin.m4a',
    'music/sharh.m4a',
    'music/duha.m4a',
    'music/lail.m4a',
    'music/shams.m4a',
    'music/balad.m4a',
    'music/fajr.m4a',
    'music/ghoshiya.m4a',
    'music/alala.m4a',
    'music/tariq.m4a',
    'music/durooj.m4a',
    'music/inshiqoq.m4a',
    'music/mutaffifin.m4a',
    'music/infitar.m4a',
    'music/takwir.m4a',
    'music/abasa.m4a',
    'music/nazi.m4a',
    'music/naba.m4a',
  ];
}

class SurahNamed {
  List<String> named = [
    ' Al Fatiha ',
    '  An-Naas ',
    '  Al-Falaq  ',
    '  Al-Ikhlaas   ',
    '  Al-Masad ',
    '  An-Nasr ',
    '  Al-Kaafiroon ',
    '  Al-Kauthar  ',
    '  Al-Maa_oon  ',
    '  Al-Quraish ',
    '  Al-Feel  ',
    '  Al-Humazah ',
    '  Al-Asr  ',
    '  At-Takaathur ',
    '  Al-Qari_ah  ',
    '  Al-Aadiyaat  ',
    '  Al-Zalzalah  ',
    '  Al-Baiyyinah  ',
    '  Al-Qadr  ',
    '  Al-Alaq ',
    '  At-Tin  ',
    '  Ash-Sharh  ',
    '  Ad-Duha  ',
    '  Al-Lail  ',
    '  Ash-Shams  ',
    '  Al-Balad  ',
    '  Al-Fajr ',
    '  Al-Ghaashiyah  ',
    '  Al-A_la  ',
    '  At-Tariq  ',
    '  Al-Burooj ',
    '  Al-Inshiqaq  ',
    '  Al-Mutaffifin  ',
    '  Al-Infitaar ',
    '  At-Takwir  ',
    '  Abasa  ',
    '  An-Nazi_aat  ',
    ' An-Naba_  ',
  ];
}
